services:
  # Server - Dev
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__OmnipulseDatabaseConnection=Server=db;Database=OmnipulseDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;
    volumes:
      - ./server:/server
    depends_on:
      - db
    networks:
      - omnipulse-network

  # Database - MS SQL Server - https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    platform: linux/amd64 # https://stackoverflow.com/questions/66662820/m1-docker-preview-and-keycloak-images-platform-linux-amd64-does-not-match-th
    environment: # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables#environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - omnipulse_sql_data:/var/opt/mssql
    networks:
      - omnipulse-network

volumes:
  omnipulse_sql_data:

networks:
  omnipulse-network:
    driver: bridge
