using AutoMapper;

using Domain.Entities;

namespace Application.MappingProfiles;

/// <summary>
/// AutoMapper profile for mapping Inspection-related commands and queries.
/// </summary>
public class InspectionMappingProfile : Profile
{
    public InspectionMappingProfile()
    {
        // CreateMap<CreateInspectionCommand, Inspection>()
        //     .ForMember(dest => dest.ID, opt => opt.Ignore()) // Auto-generated by DB
        //     .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set by BaseEntity
        //     .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by BaseEntity
        //     .ForMember(dest => dest.InspectionForm, opt => opt.Ignore()) // Navigation Property
        //     .ForMember(dest => dest.Vehicle, opt => opt.Ignore()) // Navigation Property
        //     .ForMember(dest => dest.User, opt => opt.Ignore()) // Navigation Property
        //     .ForMember(dest => dest.InspectionPassFailItems, opt => opt.Ignore()); // Navigation Collection
    }
}