using Application.Features.InspectionFormItems.Command.CreateInspectionFormItem;

using AutoMapper;

using Domain.Entities;

namespace Application.MappingProfiles;

/// <summary>
/// AutoMapper profile for mapping InspectionFormItem-related commands and queries.
/// </summary>
public class InspectionFormItemMappingProfile : Profile
{
    public InspectionFormItemMappingProfile()
    {
        // CreateInspectionFormItem
        CreateMap<CreateInspectionFormItemCommand, InspectionFormItem>(MemberList.Destination)
            .ForMember(dest => dest.ID, opt => opt.Ignore()) // Auto-generated by DB
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.InspectionForm, opt => opt.Ignore()); // Navigation Property
    }
}