using Application.Features.InspectionForms.Command.CreateInspectionForm;

using AutoMapper;

using Domain.Entities;

namespace Application.MappingProfiles;

public class InspectionFormMappingProfile : Profile
{
    public InspectionFormMappingProfile()
    {
        // CreateInspectionForm
        CreateMap<CreateInspectionFormCommand, InspectionForm>(MemberList.Destination)
            .ForMember(dest => dest.ID, opt => opt.Ignore()) // Auto-generated by DB
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.Inspections, opt => opt.Ignore()) // Navigation Collection
            .ForMember(dest => dest.InspectionFormItems, opt => opt.Ignore()); // Navigation Collection
    }
}