using System;

using Application.Features.InventoryItems.Command.CreateInventoryItem;
using Application.Features.InventoryItems.Command.UpdateInventoryItem;
using Application.Features.InventoryItems.Query.GetAllInventoryItem;
using Application.Features.InventoryItems.Query.GetInventoryItem;

using AutoMapper;

using Domain.Entities;

namespace Application.MappingProfiles;

public class InventoryItemMappingProfile : Profile
{
    public InventoryItemMappingProfile()
    {
        // CreateInventoryItem
        CreateMap<CreateInventoryItemCommand, InventoryItem>()
            .ForMember(dest => dest.ID, opt => opt.Ignore()) // Auto-generated by DB
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.Inventories, opt => opt.Ignore()) // Navigation Collection
            .ForMember(dest => dest.WorkOrderLineItems, opt => opt.Ignore()); // Navigation Collection

        // UpdateInventoryItem
        CreateMap<UpdateInventoryItemCommand, InventoryItem>()
            .ForMember(dest => dest.ID, opt => opt.MapFrom(src => src.InventoryItemID)) // Map the command's InventoryItemID to the entity's ID
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Handled by BaseEntity
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Handled by BaseEntity
            .ForMember(dest => dest.Inventories, opt => opt.Ignore()) // Navigation collection
            .ForMember(dest => dest.WorkOrderLineItems, opt => opt.Ignore()); // Navigation collection

        // GetInventoryItem
        CreateMap<InventoryItem, GetInventoryItemDTO>()
            .ForSourceMember(src => src.Inventories, opt => opt.DoNotValidate()) // Navigation Property - not included in DTO
            .ForSourceMember(src => src.WorkOrderLineItems, opt => opt.DoNotValidate()) // Navigation Property - not included in DTO
            .ForSourceMember(src => src.CreatedAt, opt => opt.DoNotValidate()) // not needed in DTO
            .ForSourceMember(src => src.UpdatedAt, opt => opt.DoNotValidate()) // not needed in DTO
            .ValidateMemberList(MemberList.Destination);

        // GetAllInventoryItem
        CreateMap<InventoryItem, GetAllInventoryItemDTO>()
            .ForSourceMember(src => src.Inventories, opt => opt.DoNotValidate()) // Navigation Property - not included in DTO
            .ForSourceMember(src => src.WorkOrderLineItems, opt => opt.DoNotValidate()) // Navigation Property - not included in DTO
            .ForSourceMember(src => src.CreatedAt, opt => opt.DoNotValidate()) // not needed in DTO
            .ForSourceMember(src => src.UpdatedAt, opt => opt.DoNotValidate()) // not needed in DTO
            .ValidateMemberList(MemberList.Destination);
    }
}