using System;
using Application.Features.InventoryItem.Command.CreateInventoryItem;
using AutoMapper;
using Domain.Entities;

namespace Application.MappingProfiles;

public class InventoryItemMappingProfile : Profile
{
    public InventoryItemMappingProfile()
    {
        CreateMap<CreateInventoryItemCommand, InventoryItem>()
            .ForMember(dest => dest.ID, opt => opt.Ignore()) // Auto-generated by DB
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore()) // Set by BaseEntity
            .ForMember(dest => dest.Inventories, opt => opt.Ignore()) // Navigation Collection
            .ForMember(dest => dest.WorkOrderLineItems, opt => opt.Ignore()); // Navigation Collection
    }
}
