import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBar, NavBar } from "./_features/shared/layout";
import Providers from "./_lib/react_query/providers";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <Providers>
          <NavBar />
          <div className="flex w-screen max-w-screen">
            <SideBar />
            <div className="flex-1 sm:w-[70%] md:w-[60%] lg:w-[50%]">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
