import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBar, NavBar } from "../components/ui/Layout";
import Providers from "../lib/react_query/providers";
import { NotificationProvider } from "@/components/ui/Feedback/NotificationProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white overflow-hidden`}
      >
        <Providers>
          <NotificationProvider>
            <NavBar />
            <SideBar />
            <main className="fixed top-16 left-64 right-0 bottom-0 overflow-auto">
              {children}
            </main>
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
