export interface VehicleListItem {
  id: string;
  name: string;
  year: number;
  make: string;
  model: string;
  vin: string;
  status: "Active" | "Inactive" | "In Shop" | "Out of Service";
  type: string;
  group: string;
  currentMeter: number;
  meterUnit: "mi" | "km" | "hr";
  licensePlate: string;
  fuelType: string;
  assignedOperator?: string;
  location?: string;
  lastServiceDate?: string;
}

export interface VehicleListFilters {
  tab: "all" | "assigned" | "unassigned" | "archived";
  search?: string;
  vehicleType?: string;
  fuelType?: string;
  vehicleStatus?: string;
  location?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
}

export const MOCK_VEHICLES = [
  {
    id: "V001",
    name: "SYD-4501",
    year: 2015,
    make: "Volvo",
    model: "7900 Electric",
    vin: "1VWA1234567890123",
    status: "Active",
    type: "City Bus",
    group: "Sydney",
    currentMeter: 84230,
    meterUnit: "km",
    licensePlate: "NSW4501",
    fuelType: "Electric",
    assignedOperator: "Anna Chen",
    location: "Sydney",
    lastServiceDate: "2024-12-01",
  },
  {
    id: "V002",
    name: "MEL-3312",
    year: 2012,
    make: "Mercedes-Benz",
    model: "Citaro",
    vin: "WDB93045678910112",
    status: "In Shop",
    type: "Tour Bus",
    group: "Melbourne",
    currentMeter: 122450,
    meterUnit: "km",
    licensePlate: "VIC3312",
    fuelType: "Diesel",
    assignedOperator: "Liam Brown",
    location: "Melbourne",
    lastServiceDate: "2025-02-10",
  },
  {
    id: "V003",
    name: "BNE-2204",
    year: 2019,
    make: "Toyota",
    model: "Coaster",
    vin: "JTFBT123456789210",
    status: "Active",
    type: "Minibus",
    group: "Brisbane",
    currentMeter: 54480,
    meterUnit: "km",
    licensePlate: "QLD2204",
    fuelType: "Petrol",
    assignedOperator: "Sophia Nguyen",
    location: "Brisbane",
    lastServiceDate: "2025-01-22",
  },
  {
    id: "V004",
    name: "CBR-1009",
    year: 2021,
    make: "Scania",
    model: "Citywide",
    vin: "YS2K1234567890345",
    status: "Inactive",
    type: "City Bus",
    group: "Canberra",
    currentMeter: 23900,
    meterUnit: "km",
    licensePlate: "ACT1009",
    fuelType: "Hybrid",
    assignedOperator: "Jake Martin",
    location: "Canberra",
    lastServiceDate: "2025-03-01",
  },
  {
    id: "V005",
    name: "SYD-8834",
    year: 2010,
    make: "Iveco",
    model: "Crossway",
    vin: "ZCFA1234567895634",
    status: "Out of Service",
    type: "Tour Bus",
    group: "Sydney",
    currentMeter: 150340,
    meterUnit: "km",
    licensePlate: "NSW8834",
    fuelType: "Diesel",
    assignedOperator: "Daniel White",
    location: "Sydney",
    lastServiceDate: "2024-09-15",
  },
  {
    id: "V006",
    name: "MEL-1920",
    year: 2017,
    make: "MAN",
    model: "Lion's City",
    vin: "WMAA1234567898912",
    status: "Active",
    type: "School Bus",
    group: "Melbourne",
    currentMeter: 69350,
    meterUnit: "km",
    licensePlate: "VIC1920",
    fuelType: "Diesel",
    assignedOperator: "Emily Zhang",
    location: "Melbourne",
    lastServiceDate: "2025-01-12",
  },
  {
    id: "V007",
    name: "BNE-3388",
    year: 2016,
    make: "Hyundai",
    model: "County",
    vin: "KMHGA1234567897654",
    status: "Active",
    type: "Minibus",
    group: "Brisbane",
    currentMeter: 47210,
    meterUnit: "km",
    licensePlate: "QLD3388",
    fuelType: "Diesel",
    assignedOperator: "Ava Roberts",
    location: "Brisbane",
    lastServiceDate: "2024-11-22",
  },
  {
    id: "V008",
    name: "CBR-0071",
    year: 2020,
    make: "Volvo",
    model: "9700",
    vin: "YV3T1234567890721",
    status: "Active",
    type: "Tour Bus",
    group: "Canberra",
    currentMeter: 33400,
    meterUnit: "km",
    licensePlate: "ACT0071",
    fuelType: "Diesel",
    assignedOperator: "Oliver Smith",
    location: "Canberra",
    lastServiceDate: "2025-02-20",
  },
  {
    id: "V009",
    name: "SYD-5611",
    year: 2013,
    make: "Hino",
    model: "Liesse",
    vin: "JHDFT1234567896532",
    status: "In Shop",
    type: "School Bus",
    group: "Sydney",
    currentMeter: 104990,
    meterUnit: "km",
    licensePlate: "NSW5611",
    fuelType: "Diesel",
    assignedOperator: "Grace Kim",
    location: "Sydney",
    lastServiceDate: "2025-03-15",
  },
  {
    id: "V010",
    name: "MEL-4488",
    year: 2018,
    make: "Fuso",
    model: "Rosa",
    vin: "JL6BG1234567890111",
    status: "Active",
    type: "Minibus",
    group: "Melbourne",
    currentMeter: 61120,
    meterUnit: "km",
    licensePlate: "VIC4488",
    fuelType: "Diesel",
    assignedOperator: "Noah Davis",
    location: "Melbourne",
    lastServiceDate: "2025-02-28",
  },
  {
    id: "V011",
    name: "SYD-8811",
    year: 2018,
    make: "Toyota",
    model: "Rosa",
    vin: "VIN113728",
    status: "Active",
    type: "School Bus",
    group: "Canberra",
    currentMeter: 118508,
    meterUnit: "km",
    licensePlate: "CAN5725",
    fuelType: "Petrol",
    assignedOperator: "Noah Davis",
    location: "Canberra",
    lastServiceDate: "2024-10-07",
  },
  {
    id: "V012",
    name: "MEL-7722",
    year: 2014,
    make: "Scania",
    model: "Crossway",
    vin: "VIN125668",
    status: "In Shop",
    type: "Tour Bus",
    group: "Melbourne",
    currentMeter: 24268,
    meterUnit: "km",
    licensePlate: "MEL9905",
    fuelType: "Petrol",
    assignedOperator: "Ava Roberts",
    location: "Melbourne",
    lastServiceDate: "2024-09-01",
  },
  {
    id: "V013",
    name: "BNE-6623",
    year: 2013,
    make: "Scania",
    model: "Rosa",
    vin: "VIN135764",
    status: "Active",
    type: "City Bus",
    group: "Sydney",
    currentMeter: 27835,
    meterUnit: "km",
    licensePlate: "SYD1351",
    fuelType: "Petrol",
    assignedOperator: "Ava Roberts",
    location: "Sydney",
    lastServiceDate: "2024-11-27",
  },
  {
    id: "V014",
    name: "CBR-5544",
    year: 2020,
    make: "MAN",
    model: "Citywide",
    vin: "VIN143000",
    status: "In Shop",
    type: "Minibus",
    group: "Sydney",
    currentMeter: 121799,
    meterUnit: "km",
    licensePlate: "SYD6511",
    fuelType: "Petrol",
    assignedOperator: "Jake Martin",
    location: "Sydney",
    lastServiceDate: "2024-05-02",
  },
  {
    id: "V015",
    name: "SYD-9933",
    year: 2010,
    make: "Volvo",
    model: "Lion's City",
    vin: "VIN152636",
    status: "In Shop",
    type: "School Bus",
    group: "Sydney",
    currentMeter: 86313,
    meterUnit: "km",
    licensePlate: "SYD1110",
    fuelType: "Hybrid",
    assignedOperator: "Emily Zhang",
    location: "Sydney",
    lastServiceDate: "2024-11-26",
  },
  {
    id: "V016",
    name: "MEL-8844",
    year: 2017,
    make: "Hino",
    model: "County",
    vin: "VIN165551",
    status: "Inactive",
    type: "Minibus",
    group: "Sydney",
    currentMeter: 102159,
    meterUnit: "km",
    licensePlate: "SYD9823",
    fuelType: "Hybrid",
    assignedOperator: "Jake Martin",
    location: "Sydney",
    lastServiceDate: "2024-02-18",
  },
  {
    id: "V017",
    name: "BNE-7766",
    year: 2019,
    make: "Hyundai",
    model: "Rosa",
    vin: "VIN177755",
    status: "In Shop",
    type: "Tour Bus",
    group: "Melbourne",
    currentMeter: 40063,
    meterUnit: "km",
    licensePlate: "MEL5539",
    fuelType: "Petrol",
    assignedOperator: "Jake Martin",
    location: "Melbourne",
    lastServiceDate: "2024-04-11",
  },
  {
    id: "V018",
    name: "CBR-6655",
    year: 2021,
    make: "Scania",
    model: "Citaro",
    vin: "VIN184685",
    status: "Out of Service",
    type: "Minibus",
    group: "Canberra",
    currentMeter: 102556,
    meterUnit: "km",
    licensePlate: "CAN1747",
    fuelType: "Diesel",
    assignedOperator: "Liam Brown",
    location: "Canberra",
    lastServiceDate: "2024-03-11",
  },
  {
    id: "V019",
    name: "SYD-1122",
    year: 2022,
    make: "Toyota",
    model: "9700",
    vin: "VIN191444",
    status: "Out of Service",
    type: "School Bus",
    group: "Canberra",
    currentMeter: 142904,
    meterUnit: "km",
    licensePlate: "CAN8815",
    fuelType: "Hybrid",
    assignedOperator: "Oliver Smith",
    location: "Canberra",
    lastServiceDate: "2024-10-21",
  },
  {
    id: "V020",
    name: "MEL-3344",
    year: 2019,
    make: "Hino",
    model: "Liesse",
    vin: "VIN205123",
    status: "Active",
    type: "Tour Bus",
    group: "Canberra",
    currentMeter: 38738,
    meterUnit: "km",
    licensePlate: "CAN1370",
    fuelType: "Petrol",
    assignedOperator: "Grace Kim",
    location: "Canberra",
    lastServiceDate: "2024-07-19",
  },
];
