export const workOrderTableColumns = [
  { key: "title", header: "Title", width: "250px" },
  { key: "vehicleName", header: "Vehicle", width: "200px" },
  { key: "workOrderTypeLabel", header: "Type", width: "120px", sortable: true },
  {
    key: "priorityLevelLabel",
    header: "Priority",
    width: "100px",
    sortable: true,
  },
  { key: "statusLabel", header: "Status", width: "120px", sortable: true },
  { key: "assignedToUserName", header: "Assigned To", width: "150px" },
  {
    key: "scheduledStartDate",
    header: "Scheduled Start",
    width: "150px",
    sortable: true,
  },
  {
    key: "actualStartDate",
    header: "Actual Start",
    width: "150px",
    sortable: true,
  },
  {
    key: "startOdometer",
    header: "Start Odometer",
    width: "120px",
    sortable: true,
  },
  { key: "endOdometer", header: "End Odometer", width: "120px" },
  { key: "totalCost", header: "Total Cost", width: "100px" },
  { key: "totalLaborCost", header: "Labor Cost", width: "100px" },
  { key: "totalItemCost", header: "Item Cost", width: "100px" },
  { key: "description", header: "Description", width: "200px" },
];
