#!/bin/sh

set -e

##############################
########## FRONTEND ##########
##############################

FRONTEND_DIR="client"
cd "$FRONTEND_DIR" || exit 1

# Linting
echo "🔍 Frontend - Lint"
npx lint-staged || {
    echo "❌ Frontend - Lint failed"
    exit 1
}

# Building
echo "🧱 Frontend - Build"
npm run build || {
    echo "❌ Frontend - Build failed"
    exit 1
}

cd ..

#############################
########## BACKEND ##########
#############################

BACKEND_DIR="server"
cd "$BACKEND_DIR" || exit 1

# Building
echo "🧱 Backend - Build"
dotnet build --nologo || {
    echo "❌ Backend - Build failed"
    exit 1
}

# Linting
echo "🔍 Backend - Lint"
dotnet format
dotnet format --verify-no-changes --verbosity quiet || {
    echo "❌ Backend - Lint failed"
    exit 1
}

# Testing
echo "🧪 Backend - Test"
dotnet test || {
    echo "❌ Backend - Test failed"
    exit 1
}

cd ..

echo "✅ All pre-commit checks passed!"
